version: '2.0'

services:

  blockchain-explorer:
    container_name: blockchain-explorer
    image: eluft84/blockchain-explorer
    # # wait-for-it waits until the mysql server is up and running
    command:  bash -c "./wait-for-it.sh -t 120 mysql-explorer:3306 -s -- node main.js"
    volumes:
      # # Do not forget to update the config file based on your config 
      - ./config.json:/blockchain-explorer/config.json
      # # Do not forget to add your cryto files
      - /composer/crypto-config:/blockchain-explorer/crypto-config
    depends_on:
      - mysql-explorer
    ports:
      - 8080:8080
 
  mysql-explorer:
    container_name: mysql-explorer
    image: mysql/mysql-server:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fabricexplorer
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./fabricexplorer.sql:/docker-entrypoint-initdb.d/fabricexplorer.sql
    ports:
      - 3306:3306


